version: '3.4'

networks:
  loss-detection-app_edgex-network:
    external: true   

services:
  cv-region-of-interest:
    image: rtsf-at-checkout/cv-region-of-interest:dev
    container_name: cv-region-of-interest
    hostname: cv-region-of-interest
    environment:
      - MQTT_DESTINATION_HOST=mqtt:1883
      - CAMERA0_ENDPOINT=http://video-analytic:8080/pipelines/object_detection_cpu_render/1
      # - CAMERA0_SRC=rtsp://admin:{PASSWORD}@{URL}:554/{STREAM-END-POINT}
      - CAMERA0_SRC=file:///home/video-analytics-serving/video-samples/grocery-test.mp4
      - CAMERA0_ROI_NAME=Staging
      - CAMERA0_CROP_TBLR=0,0,0,0
    networks:
      - loss-detection-app_edgex-network
    depends_on:
      - video-analytic

  video-analytic:
    image: video-analytics-serving-gstreamer:latest
    ports:
      - "8090:8080"
    container_name: video-analytic
    hostname: video-analytic
    privileged: true
    networks:
      - loss-detection-app_edgex-network
    environment:
      DISPLAY: ${DISPLAY}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./pipelines:/home/video-analytics-serving/pipelines
      - ./models:/home/video-analytics-serving/models
      - ./video-samples:/home/video-analytics-serving/video-samples
