version: "3.4"

networks:
  loss-detection-app_edgex-network:
    external: true

volumes:
  rsp-cache:
  rsp-config:
  
services:
  rsp-mqtt-device-service:
    image: rsp/mqtt-device-service:dev
    container_name: rsp-mqtt-device-service
    networks:
      - loss-detection-app_edgex-network
    extra_hosts:
      - "mosquitto-server:172.17.0.1"
    volumes:
      - ./res/rsp-mqtt-device-service/docker:/res/docker
      - ./res/rsp-mqtt-device-service/schemas/inventory_event_schema.json:/res/schemas/incoming/inventory_event_schema.json

  rsp-avahi:
    image: rsp/avahi:0.1
    container_name: rsp-avahi
      # environment:
      # LOG_LEVEL: debug
      # CAP_HOST_MANAGEMENT: 1
    # ipc: host
    network_mode: host
    # pid: host
    # userns_mode: host
    privileged: true
    restart: "on-failure:5"
    # networks:
      # - rsp_gw_net
    volumes:
      - /var/run/dbus:/var/run/dbus
    # deploy:
      # mode: global
      # placement:
        # constraints: [node.platform.os == linux]

  rsp-ntp:
    image: rsp/ntp:0.1
    container_name: rsp-ntp
    network_mode: host
    cap_add:
     - SYS_TIME
    restart: "on-failure:5"


  rsp-gw:
    image: rsp/sw-toolkit-gw:0.1
    container_name: rsp-gw
    environment:
      DOCKER_HOST_IP: ${HOST_IP}
      DOCKER_HOSTNAME: ${HOSTNAME}
      # LOG_LEVEL: debug
      # CAP_HOST_MANAGEMENT: 1
    # ipc: host
    network_mode: host
    # pid: host
    # privileged: true
    # userns_mode: host
    restart: "on-failure:5"
    volumes:
      - rsp-cache:/opt/rsp-sw-toolkit-gw/cache/
      - rsp-config:/opt/rsp-sw-toolkit-gw/config/
    # networks:
      # rsp_gw_net:
        # aliases:
          # - ${HOSTNAME}
    ports:
      - 5222:5222
      - 8080:8080
      - 8443:8443
    # deploy:
      # mode: global
      # placement:
        # constraints: [node.platform.os == linux]