# Copyright (C) 2019 Intel Corp.
# 
# SPDX-License-Identifier: Apache-2.0

[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = ' event-reconciler'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'Event Reconciler has started'
Timeout = '30s'

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.Data]
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = '30s'

  [Clients.Logging]
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Binding]
 Type="messagebus"
 SubscribeTopic="events"
 PublishTopic="suspect-list"

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'edgex-core-data'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = true

[ApplicationSettings]
  DeviceNames = "device-pos-rest, device-pos-mqtt, device-scale, device-scale-rest, device-scale-mqtt, device-cv-roi-rest, device-cv-roi-mqtt, device-rfid-roi-rest, device-rfid-roi-mqtt"
  DevicePos = "device-pos"
  DeviceScale = "device-scale"
  DeviceCV = "device-cv-roi"
  DeviceRFID = "device-rfid-roi"
  ProductLookupEndpoint = "product-lookup:8083"
  WebSocketPort = "9083"
  ScaleToScaleTolerance = "0.02"
  CvTimeAlignment = '-5s'
