runner:
  bandit:
    cmd:  'bandit -r ./ -f custom --msg-template "{relpath}:{line}:{col}:{test_id}:{severity}:{msg}" | tee "$PWD"/scan_results/banditResults.txt' 
    errorformat: # (optional if you use `format`)
      - "%f:%l:%c:%m" 
    name: bandit # (optional. you can overwrite <tool-name> defined by runner key)
    level: info # (optional. same as -level flag. [info,warning,error])
  hadolint_rtsf-at-checkout-cv-region-of-interest:
    cmd: './bin/hadolint -c .github/.hadolint.yaml rtsf-at-checkout-cv-region-of-interest/Dockerfile -f json | jq -f ".github/.rdjson.jq" -c | tee "$PWD"/scan_results/hadolintResults-rtsf-at-checkout-cv-region-of-interest.txt'
    format: rdjson
    level: error # (optional. same as -level flag. [info,warning,error])
  hadolint_rtsf-at-checkout-device-scale:
    cmd: './bin/hadolint -c .github/.hadolint.yaml rtsf-at-checkout-device-scale/Dockerfile -f json | jq -f ".github/.rdjson.jq" -c | tee "$PWD"/scan_results/hadolintResults-rtsf-at-checkout-device-scale.txt'
    format: rdjson
    level: error # (optional. same as -level flag. [info,warning,error])
  shellcheck:
    cmd: shellcheck **/*.sh -f gcc | tee "$PWD"/scan_results/shellcheckResults.txt
    errorformat: 
      - "%f:%l:%c:%m" 
  pep8:
    cmd: pep8 **/*.py | tee "$PWD"/scan_results/pep8Results.txt
    format: pep8
  golangci-lint:
    cmd: make lint
    format: golangci-lint
