site_name: Real Time Sensor Fusion for Loss Detection at Checkout
docs_dir: ./docs_src
site_dir: ./docs
theme:
  name: 'material'
plugins: []
nav:
  - 'index.md'
  - Phases:
      - './phases/phase1.md'
      - './phases/phase2.md'
      - './phases/phase3.md'
  - "RTSF at Checkout Events":
    - './rtsf_at_checkout_events/checkout_events.md'
    - './rtsf_at_checkout_events/event_simulation.md'
  - 'device_services.md'
  - 'configuration.md'
  - 'notifications.md'
  - 'troubleshooting.md'
  - 'references.md'
google_analytics:
  - 'UA-154731555-1'
  - 'auto'
extra_css:
  - 'https://fonts.googleapis.com/icon?family=Material+Icons'
  - './stylesheets/extra.css'
extra_javascript:
  - 'https://unpkg.com/lunr/lunr.js'
markdown_extensions:
  - codehilite
  - admonition