# Copyright (C) 2019 - 2020 Intel Corp.
# 
# SPDX-License-Identifier: Apache-2.0

[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48096
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'Starting Loss Detector'
Timeout = '30s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'


[Clients]
  [Clients.CoreData]
  Protocol = "http"
  Host = "localhost"
  Port = 48080

  [Clients.Notifications]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48060

[MessageBus]
Type = 'zero'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5564
        Protocol = 'tcp'
        
[Binding]
 Type="messagebus"
 SubscribeTopic="suspect-list"

[Logging]
EnableRemote = false
File = ""

[ApplicationSettings]
NotificationsURL = "http://localhost:48060"
NotificationEmailAddresses = "cloud@abc.def,jack@abc.def"
NotificationSlug = "sys-admin"
