# Copyright (C) 2019 Intel Corp.
# 
# SPDX-License-Identifier: Apache-2.0

[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'rsp-event-handler'
Port = 48096
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'RSP Event Handler App has started'
Timeout = '30s'

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.CoreData]
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = '30s'

  [Clients.Logging]
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Binding]
 Type="messagebus"
 SubscribeTopic="events"

[MessageBus]
Type = 'zero'
    [MessageBus.SubscribeHost]
        Host = 'edgex-core-data'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = true

[ApplicationSettings]
DeviceNames = "rsp-controller"
ValueDescriptorToFilter = "inventory_event"
  
