# Copyright (C) 2019 - 2020 Intel Corp.
# 
# SPDX-License-Identifier: Apache-2.0

[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48096
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'RSP Event Handler App has started'
Timeout = '30s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.CoreData]
  Protocol = "http"
  Host = "localhost"
  Port = 48080

[Binding]
 Type="messagebus"
 SubscribeTopic="events"

[MessageBus]
Type = 'zero'
    [MessageBus.SubscribeHost]
        Host = 'localhost'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = false
File = ""

[ApplicationSettings]
DeviceNames = "rsp-controller"
ValueDescriptorToFilter = "inventory_event"
